#!/bin/python

import math
import os
import random
import re
import sys

# Given an integer, , perform the following conditional actions:
#
# If  is odd, print Weird
# If  is even and in the inclusive range of 2 to 5, print Not Weird
# If  is even and in the inclusive range of 6 to 20, print Weird
# If  is even and greater than , print Not Weird
# Complete the stub code provided in your editor to print whether or not  is weird.
from pip._vendor.distlib.compat import raw_input

if __name__ == '__main__':
    N = int(raw_input())
    if N % 2 != 0:
        print("Weird")
    elif N % 2 == 0 and N >= 2 and N <= 5:
        print("Not Weird")
    elif N % 2 == 0 and N >= 6 and N <= 20 :
        print("Weird")
    elif N % 2 == 0 and N > 20:
        print("Not Weird")

